# Generated by Django 5.0.2 on 2024-05-20 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kritikApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('custom_id', models.AutoField(primary_key=True, serialize=False)),
                ('path_image', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('ai_script', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('custom_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_comment', models.TextField(blank=True, default='')),
                ('star_rating', models.FloatField(default=0)),
                ('image_path', models.CharField(blank=True, default='', max_length=255)),
                ('establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kritikApp.establishment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
